""" Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:
    Triangle:   T(n)=n(n+1)/2
    Pentagonal: P(n)=n(3n-1)/2
    Hexagonal:  H(n)=n(2n-1)

It can be verified that T(285) == P(165) == H(143) == 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import euler.utils.numtheory

def tph_integers():
    """ Since triangular numbers are a subset of hexagonal, we need m, n such
    that:
        P(n) == H(m)  ->  (1/2)n(3n-1) == m(2m-1)
    We complete the square, rearrange, simplify, etc to get:
    (1)    (6n-1)^2 - 3(4m-1)^2 == -1
    Set x=6n-1 and y=4m-1. We need solutions (x, y) to the Pell-like equation:
    (2)    x^2 - 3y^2 = -2
    which happen to satisfy x=5(mod 6) and y=3(mod 4)

    We know that n=165, m=143 solves (1), so -> x=p=989, y=q=571 solves (2).

    Let r, s be solutions to the "unit" (Pell equation) form of (2):
    (3)    x^2 - 3y^2 = 1
    Then we can use the identity:
    (4)    (p^2-Dq^2)(r^2-Ds^2) = (pr+-Dqs)^2 - D(ps+-qr)^2 = c
    with D=3 and c=-2 to construct larger solutions (x, y)=(pr+-Dqs, ps+-qr)
    to (2). We need to use incrementally larger values of (r, s) which can be
    computed using Pell techniques.

    Should yield:
        1, 40755, 1533776805, 57722156241751
    """
    yield 1     # One is the trivial solution
    yield 40755 # Yield our known lowest triangular-pentagonal-hexagonal number
    p, q, D = 989, 571, 3
    pell_seq = euler.utils.numtheory.solve_pell(D)
    for r, s in pell_seq:
        x, y = p*r-D*q*s, p*s-q*r
        if x % 6 == 5 and y % 4 == 3 and x>0 and y>0:
            m = (y+1)/4
            yield m*(2*m-1)
        x, y = p*r+D*q*s, p*s+q*r
        if x % 6 == 5 and y % 4 == 3 and x>0 and y>0:
            m = (y+1)/4
            yield m*(2*m-1)

def ANSWER():
    tph = tph_integers()
    next(tph) and next(tph)
    return next(tph)

if __name__ == '__main__':
    import euler.utils
    euler.utils.solution_printer(ANSWER)

